# Site settings
title: CureFFI.org
twitter_username: cureffi
github_username: ericminikel
description: "Not if, when."
baseurl: ""
url: "http://www.cureffi.org"
future: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
