options(stringsAsFactors=FALSE)

source('~/d/sci/src/miscellanea/r_helper.r')
chbr = read.table('~/d/sci/037cinf/data/chbr_prop.txt',sep='\t',header=TRUE)
acbbb = read.table('~/d/sci/037cinf/acbbb_prop.txt',sep='\t',header=TRUE)
png('~/d/j/cureffi/media/2015/12/fragment_mwt_comparison.png',width=800,height=400,res=100)
par(mar=c(4,5,1,2))
hist(chbr$MWT, breaks=(0:60)*10, freq=FALSE, col=alpha('#FF2015',.5), border=NA, axes=FALSE, main='', xlab='', ylab='', yaxs='i', xaxs='i',ylim=c(0,.0105))
par(new=TRUE)
hist(acbbb$MWT, breaks=(0:60)*10, freq=FALSE, col=alpha('#343411',.5), border=NA, axes=FALSE, main='', xlab='', ylab='', yaxs='i', xaxs='i',ylim=c(0,.0105))
axis(side=1, at=(0:6)*100, labels=(0:6)*100)
axis(side=2, at=(0:5)*.002, labels=percent((0:5)*.002), las=2)
mtext(side=1,line=2.5,text='molecular weight')
mtext(side=2,line=3.5,text='proportion of compounds')
legend_text = paste(c('ACB Building Blocks (fragment)','Chembridge (conventional)'),', mean MW = ',formatC(c(mean(acbbb$MWT),mean(chbr$MWT)),format='f',digits=0),', N = ',formatC(c(nrow(acbbb),nrow(chbr)),format='f',digits=0,big.mark=','),sep='')
legend('topright',legend_text,col=alpha(c('#343411','#FF2015'),.5),pch=15,bty='n',cex=.8)
dev.off()